<a href="https://colab.research.google.com/github/siva140887/data-visualization-programs/blob/main/Datavisualization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lab 1

Q1

In [ ]:
# Integers
a = input("Enter number1")
a = int(a)

b = input("Enter number2")
b = int(b)

add = a + b
print("addition result is:",add)
sub = a - b
print("addition result is:",sub)
mul = a * b
print("addition result is:",mul)
div = a / b
print("addition result is:",div)

# Floats
a = input("Enter number1")
a = float(a)

b = input("Enter number2")
b = float(b)

add = a + b
print("addition result is:",add)
sub = a - b
print("addition result is:",sub)
mul = a * b
print("addition result is:",mul)
div = a / b
print("addition result is:",div)

# Strings
a = input("Enter string1")
b = input("Enter string2")

print("String1:",a)
print("String2:",b)

# using switch
a = input("Enter number1")
a = int(a)

b = input("Enter number2")
b = int(b)

choice = int(input("Enter the choice"))
match choice:
  case 1:
    add = a + b
    print("addition result is:",add)
  case 2:
    sub = a - b
    print("addition result is:",sub)
  case 3:
    mul = a * b
    print("addition result is:",mul)
  case _:
    div = a / b
    print("addition result is:",div)

Enter number110
Enter number220
addition result is: 30
addition result is: -10
addition result is: 200
addition result is: 0.5
Enter number121.5
Enter number211
addition result is: 32.5
addition result is: 10.5
addition result is: 236.5
addition result is: 1.9545454545454546
Enter string1abc
Enter string2def
String1: abc
String2: def
Enter number112
Enter number224
Enter the choice6
addition result is: 0.5


Q2

In [ ]:
def prime(number):
  count = 0
  for i in range(2,number,1):
    if(number%i==0):
      count = count + 1
  if(count>0):
    return True

  else:
    return False

number = int(input("Enter the number"))
print("status",prime(number))

# elif
def prime(number):
  count = 0
  for i in range(2,number,1):
    if(number%i==0):
      count = count + 1
  if(count>0):
    return True

  elif(count==0):
    return False

number = int(input("Enter the number"))
print("status",prime(number))

Enter the number7
status False
Enter the number9
status True


Q3

In [ ]:
print("The numbers are:")
for i in range(1,101,1):
  print(i)

sum=0
print("The odd numbers are:")
for i in range(1,101,1):
  if(i%2!=0):
    print(i)
  else:
    sum = sum + i
print("The sum of even numbers is:", sum)


The numbers are:
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
The odd numbers are:
1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
51
53
55
57
59
61
63
65
67
69
71
73
75
77
79
81
83
85
87
89
91
93
95
97
99
The sum of even numbers is: 2550


Q5

In [ ]:
a = input("Enter the string")

n = len(a)

consonants=0
vowels=0

for i in range(n):
  if(a[i] == 'a' or a[i] == 'e' or a[i] == 'i' or a[i] == 'o' or a[i] == 'u'):
    vowels = vowels + 1
  else:
    if(a[i]!=' '):
      consonants = consonants + 1

print("vowels:",vowels)
print("consonants:",consonants)



Enter the stringhi hello world
vowels: 4
consonants: 8


Q4

In [ ]:
def plus(ele1,ele2):
  return ele1 + ele2

print("Integer addition",plus(1,2))
print("Float addition",plus(1.43,2.47))
print("String concat",plus("abc","def"))





Integer addition 3
Float addition 3.9000000000000004
String concat abcdef


Lab 2

Q1

In [ ]:
nos = []   # empty list. Both read and write operations are allowed

no = int(input("How many numbers to be inputted to the list?"))

print("Enter the numbers:")
for i in range(no):
  temp = int(input())
  nos.append(temp)
print(nos)  # printing the list

largest = max(nos)
smallest = min(nos)
sum1 = 0
for val in nos:
  sum1 = sum1 + val
average = sum1/no

print("largest:", largest)
print("smallest:", smallest)
print("sum:", sum1)
print("average:", average)  # printing the results

ele = int(input("Enter the number of interest:"))
print("The no. of occurrences is:", nos.count(ele))

How many numbers to be inputted to the list?6
Enter the numbers:
12
11
10
14
15
10
[12, 11, 10, 14, 15, 10]
largest: 15
smallest: 10
sum: 72
average: 12.0
Enter the number of interest:14
The no. of occurrences is: 1


Q2

In [ ]:
# creating empty tuple
tuple1 = ()
print(tuple1)

# Read access
for val in tuple1:
  print("the current element is:", val)

# creating tuple
tuple1 = (1,2,3,4,5)
print(tuple1)

# Read access
for val in tuple1:
  print("the current element is:", val)

# creating tuple with mixed data
tuple1 = (1,2.5,"abc",True)
print(tuple1)

# Read access
for val in tuple1:
  print("the current element is:", val)

# creating single-element tuple
tuple1 = (1,)
print(tuple1)

# read access
for val in tuple1:
  print("the current element is:", val)

# write access
try:
  tuple1[0] = 45
except TypeError as e:
  print("Error:",e)
  print("Write access not allowed")


()
(1, 2, 3, 4, 5)
the current element is: 1
the current element is: 2
the current element is: 3
the current element is: 4
the current element is: 5
(1, 2.5, 'abc', True)
the current element is: 1
the current element is: 2.5
the current element is: abc
the current element is: True
(1,)
the current element is: 1
Error: 'tuple' object does not support item assignment
Write access not allowed


Q3

In [ ]:
winners = {
    1975: "West Indies",
    1979: "West Indies",
    1983: "India",
    1987: "Australia",
    1992: "Pakistan",
    1996: "Sri Lanka",
    1999: "Australia",
    2003: "Australia",
    2007: "Australia",
    2011: "India",
    2015: "Australia",
    2019: "England",
    2023: "Australia"
}

wins = {}
for country in winners.values():
  wins[country] = wins.get(country,0) + 1
# printing wins
print(wins)

# Identifying the country that performed the best

best_country = next(iter(wins))
#max1 = wins[best_country]
#print(best_country)
#print(max1)

for country in wins.keys():
  if(wins[best_country] < wins[country]):
    best_country = country
print(best_country, wins[best_country])

# Displaying unique list
unique_list = set(winners.values())
print(unique_list)



{'West Indies': 2, 'India': 2, 'Australia': 6, 'Pakistan': 1, 'Sri Lanka': 1, 'England': 1}
Australia 6
{'West Indies', 'India', 'England', 'Sri Lanka', 'Australia', 'Pakistan'}


Q4

In [ ]:
sentence = input("Enter the sentence")
list = sentence.split()
print(list)  # split sentence into words

dict = {}
for word in list:
  dict[word] = dict.get(word,0) + 1

print(dict)


Enter the sentencehi hello world hi world 
['hi', 'hello', 'world', 'hi', 'world']
{'hi': 2, 'hello': 1, 'world': 2}


Q5

In [ ]:
# set is an unordered collection of unique and mutable items. unordered means elements cannot be accessed by index
set1 = set()
print(set1)

no1 = int(input("Enter the no. of elements"))

for i in range(no1):
  ele = int(input())
  set1.add(ele)

print(set1)

set2 = set()
print(set2)

no1 = int(input("Enter the no. of elements"))

for i in range(no1):
  ele = int(input())
  set2.add(ele)

print(set2)

# Union
print(set1.union(set2))

# Intersection
print(set1.intersection(set2))

# Difference
print(set1.difference(set2))

set()
Enter the no. of elements5
1
2
3
4
5
{1, 2, 3, 4, 5}
set()
Enter the no. of elements5
6
7
1
2
3
{1, 2, 3, 6, 7}
{1, 2, 3, 4, 5, 6, 7}
{1, 2, 3}
{4, 5}


Lab 3

Sample

In [ ]:
# Creating 1D array
import numpy as np
arr1 = np.array([1,2,3,4,5,6])
print(arr1)

# Creating 2D array
arr2 = np.array([[1,2],[4,5],[7,8],[9,10]])
print(arr2)

# Creating 1D array with zeros
arr3 = np.zeros(10)
print(arr3)

# Creating 2D array with zeros
arr4 = np.zeros((4,3))
print(arr4)

# Creating array with a range of values
arr5 = np.arange(10,50,4)
print(arr5)

# Creating array with evenly spaced values
arr6 = np.linspace(0,1,8)
print(arr6)

# Creating array with user inputted values
n = int(input("Enter no. of elements"))
arr7 = np.zeros(n)

for i in range(n):
  arr7[i] = int(input())

print(arr7)


[1 2 3 4 5 6]
[[ 1  2]
 [ 4  5]
 [ 7  8]
 [ 9 10]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[10 14 18 22 26 30 34 38 42 46]
[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.        ]
Enter no. of elements5
41
42
43
44
45
[41. 42. 43. 44. 45.]


Q1

In [ ]:
import numpy as np

arr1 = np.random.randint(1,51,size=(3,4))
print(arr1)

# Computing mean, median, stddev

mean1 = np.mean(arr1)
print(mean1)

median1 = np.median(arr1)  # axis = 0 means columnwise, axis = 1 means rowwise
print(median1)

stddev = np.std(arr1)
print(stddev)

# Sum of all elements, Sum of each row
sumall = np.sum(arr1)
print(sumall)

sumrow = np.sum(arr1,axis=1)
print(sumrow)

# Reshaping the array into 2*6
newarr = np.reshape(arr1,(2,6))
print(newarr)



[[33 17 14  7]
 [ 4 45  9 32]
 [ 5  8 26 28]]
19.0
15.5
12.864680330268607
228
[71 90 67]
[[33 17 14  7  4 45]
 [ 9 32  5  8 26 28]]


Q2

In [ ]:
# Two 3x3 matrices
Mat1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(Mat1)

Mat2 = np.array([[3,2,1],[6,5,4],[9,8,7]])
print(Mat2)

# Matrix addition
add = Mat1 + Mat2
print(add)

# Matrix subtraction
sub = Mat1 - Mat2
print(sub)

# Matrix mul - element type
mul1 = Mat1 * Mat2
print(mul1)

# Matrix mul - dot type
mul2 = np.dot(Mat1,Mat2)
print(mul2)

# Determinant of matrix
detMat1 = np.linalg.det(Mat1)
print(detMat1)

# Inverse of matrix
if(detMat1!=0):
  invMat1 = np.linalg.inv(Mat1)
  print(invMat1)

else:
  print("inverse does not exist")

# Transpose of matrix
print(Mat1.T)
print(Mat2.T)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[ 4  4  4]
 [10 10 10]
 [16 16 16]]
[[-2  0  2]
 [-2  0  2]
 [-2  0  2]]
[[ 3  4  3]
 [24 25 24]
 [63 64 63]]
[[ 42  36  30]
 [ 96  81  66]
 [150 126 102]]
0.0
inverse does not exist
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[3 6 9]
 [2 5 8]
 [1 4 7]]


Lab 4

Q1

In [2]:
import pandas as pd

# List of daily temperatures
temperatures = [12,13,14,15,16,17,19]

# Days of the week as index labels
days = ['Monday','Tuesday','Wednesday','Thursday', 'Friday', 'Saturday', 'Sunday']

# Creating pandas series
pdseries = pd.Series(temperatures, index=days)

# Printing the series
print(pdseries)




Monday       12
Tuesday      13
Wednesday    14
Thursday     15
Friday       16
Saturday     17
Sunday       19
dtype: int64
